(let* ((gmd (file-name-directory
	     (or load-file-name buffer-file-name)))
       (gimp-dir
	(expand-file-name 
	 (read-file-name "Please enter config directory for the GIMP: "
			 "~/.gimp-2.4/"
			 "~/.gimp-2.4/")))
       (gimp-emacs-dir (expand-file-name (concat gimp-dir "/emacs/")))
       (emacs-interaction.scm "emacs-interaction.scm")
       (emacs-interaction.scm-target
	(expand-file-name 
	 (mapconcat 'identity
		    (list gimp-dir
			  "scripts"
			  emacs-interaction.scm)
		    "/")))
       (gimp-init-file (concat gmd "gimp-init.el")))
  (unless (file-exists-p gimp-emacs-dir)
    (message "Making directory %s for communication emacs<->gimp..."
	     gimp-emacs-dir
	     (make-directory gimp-emacs-dir)))
  (message "Installing %s..." emacs-interaction.scm-target)
  (apply
   (if (fboundp 'make-symbolic-link)
       'make-symbolic-link
     'copy-file)
   (list 
    (expand-file-name (concat gmd emacs-interaction.scm))
    emacs-interaction.scm-target
    t))
  
  (progn
    (find-file-literally (concat gmd "gimp-vars.el"))
    (erase-buffer)
    (insert ";;This file was autogenerated by gimp-install, do not modify")
    (print 
     `(defcustom gimp-dir (expand-file-name ,gimp-dir)
	"Fall-back user directory for the GIMP.

the GIMP puts its caches here.  Retrieve it by evaluating the variable
`gimp-dir' in GIMP script-fu console.

It is advised to run `gimp-install.el' (or the shell script
install.sh in the source directory) to change this variable and
stuff depending on it."
	:group 'gimp-directories
	:type 'string) 
     (current-buffer))
    (save-buffer)
    (kill-buffer (current-buffer)))

  (load gimp-init-file)
  (byte-compile-file 
   (concat gmd "gimp-mode.el"))
  (message "
Installation of gimp-mode completed.
====================================

Put the following in your load file: %S

Please see the file README for further instructions."
	   `(load ,(concat gmd "gimp-init.el"))))



